"""Gherkin @sdk scan → Lab matrix/sdk.yaml."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, cast

try:
    from gherkin.parser import Parser
except ImportError as exc:
    raise RuntimeError("gherkin-official package required for sdk_sync") from exc

from labs.lib.python.matrix.zone_lookup import country_to_zone

SCOPE_PROVIDER_PREFIX = "provider:"
CONCERN_ALIASES = {
    "delivery_resolution": "resolution",
    "api_comprehensive_testing": "pricing",
}

WEIGHT_RE = re.compile(
    r"(?:the letter weight is|weight is|weight)\s+(\d+)\s*grams?",
    re.IGNORECASE,
)
PRODUCT_ID_RE = re.compile(
    r'(?:product id is|product_id is|product is)\s+"([a-z0-9_]+)"',
    re.IGNORECASE,
)
ENVELOPE_RE = re.compile(
    r'(?:envelope id is|envelope is|envelope)\s+"([A-Z0-9]+)"',
    re.IGNORECASE,
)
COUNTRY_RE = re.compile(
    r'(?:I want to send a letter to country|destination country|the destination country is)\s+"([A-Z]{2})"',
    re.IGNORECASE,
)
ZONE_ASSERT_RE = re.compile(r'zone with id "([a-z0-9_]+)"', re.IGNORECASE)
REGION_RE = re.compile(r"UA-\d+")

FILE_HEADER = """\
# SDK layer index — pointers to Gherkin only (no duplicated scenario text).
# cell_id: {provider}.{concern}.{slice}.{product_id}.{zone}
# GENERATED by Porto SDK Lab scripts/matrix-sdk-sync.py — do not hand-edit refs.

schema_version: 1

sdk_cells:
"""


def _feature_tags(feature: dict) -> set[str]:
    tags: set[str] = set()
    for tag in feature.get("tags", []):
        name = tag.get("name", "")
        if name.startswith("@"):
            tags.add(name[1:])
    return tags


def _iter_scenario_nodes(feature: dict) -> list[dict]:
    nodes: list[dict] = []
    for child in feature.get("children", []):
        if child.get("scenario"):
            nodes.append(child)
        elif child.get("rule"):
            for rule_child in child["rule"].get("children", []):
                if rule_child.get("scenario"):
                    nodes.append(rule_child)
    return nodes


def _scenario_step_text(scenario_obj: dict) -> str:
    lines: list[str] = []
    for step in scenario_obj.get("steps", []):
        text = step.get("text", "")
        if text:
            lines.append(text)
        for row in step.get("argument", {}).get("rows", []):
            for cell in row.get("cells", []):
                value = cell.get("value", "")
                if value:
                    lines.append(value)
    return "\n".join(lines)


def _provider_from_context(rel_path: Path, feature_tags: set[str]) -> str:
    if "core" in feature_tags:
        return "global"
    for tag in feature_tags:
        if tag.startswith(SCOPE_PROVIDER_PREFIX):
            return tag[len(SCOPE_PROVIDER_PREFIX) :]
    parts = rel_path.parts
    if "providers" in parts:
        idx = parts.index("providers")
        if idx + 1 < len(parts):
            return parts[idx + 1]
    return "global"


def _concern_from_path(rel_path: Path) -> str:
    stem = rel_path.stem.replace("-", "_")
    return CONCERN_ALIASES.get(stem, stem)


def _extract_resolution_key(text: str) -> str | None:
    for pattern in (PRODUCT_ID_RE, ENVELOPE_RE, WEIGHT_RE):
        match = pattern.search(text)
        if match:
            return match.group(1)
    return None


def _extract_country(text: str) -> str | None:
    match = COUNTRY_RE.search(text)
    return match.group(1) if match else None


def _extract_zone(
    text: str,
    provider: str,
    country: str | None,
    *,
    porto_data_path: Path | None,
) -> str | None:
    region = REGION_RE.search(text)
    if region:
        return region.group(0)

    zone_match = ZONE_ASSERT_RE.search(text)
    if zone_match:
        return zone_match.group(1)

    if country and porto_data_path is not None:
        zone = country_to_zone(provider, country, porto_data_path=porto_data_path)
        if zone:
            return zone

    if "restricted country" in text.lower():
        return "restricted"
    return None


def _infer_slice(scenario_name: str, text: str, keyword: str) -> str:
    if keyword == "Scenario Outline":
        return "matrix"

    name = scenario_name.lower()
    body = text.lower()

    if "ua-14" in name or "ua-14" in body or "prohibited" in body:
        return "prohibited"
    if any(token in name for token in ("invalid", "reject", "missing", "too heavy", "exceeding")):
        return "invalid_input"
    if "ambiguous" in name or "disambiguation" in name:
        return "disambiguation"
    if any(token in name for token in ("restriction", "sanctions", "restricted country")):
        return "restriction"
    if "warning" in name or "edge case" in name:
        return "scope"
    if "service" in name or "registered" in name or "mark profile" in name:
        return "service_variant"
    if any(
        token in name
        for token in (
            "metadata",
            "registry",
            "list",
            "catalog",
            "manifest",
            "envelope",
            "integrations",
            "access ",
        )
    ):
        return "metadata"
    if "cli" in name or "cli " in body:
        return "metadata"
    if "weight" in name and any(token in name for token in ("boundary", "tier", "maximum")):
        return "weight_boundary"
    if "simulate" in name:
        return "happy"
    return "happy"


def _slug_suffix(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return slug[:32]


def _make_cell_id(
    provider: str,
    concern: str,
    slice_name: str,
    product_id: str | None,
    zone: str | None,
    scenario_name: str,
    used: set[str],
) -> str:
    parts = [provider, concern, slice_name, product_id or "null", zone or "null"]
    base = ".".join(parts)
    cell_id = base
    if cell_id in used:
        cell_id = f"{base}.{_slug_suffix(scenario_name)}"
        counter = 2
        while cell_id in used:
            cell_id = f"{base}.{_slug_suffix(scenario_name)}_{counter}"
            counter += 1
    used.add(cell_id)
    return cell_id


def _matrix_ref(rel_path: Path, keyword: str, scenario_name: str) -> str:
    ref_path = rel_path.as_posix()
    if keyword == "Scenario Outline":
        return f"{ref_path}:Scenario Outline:{scenario_name}"
    return f"{ref_path}:Scenario:{scenario_name}"


def scan_sdk_features(
    features_dir: Path,
    *,
    porto_data_path: Path | None = None,
) -> list[dict[str, Any]]:
    sdk_root = features_dir / "sdk"
    if not sdk_root.is_dir():
        return []

    parser = Parser()
    cells: list[dict[str, Any]] = []
    used_ids: set[str] = set()

    for feature_path in sorted(sdk_root.rglob("*.feature")):
        gherkin_document = parser.parse(feature_path.read_text(encoding="utf-8"))
        feature_raw = gherkin_document.get("feature")
        if not feature_raw:
            continue
        feature = cast(dict[str, Any], feature_raw)

        feature_tags = _feature_tags(feature)
        if "sdk" not in feature_tags:
            continue

        rel_path = feature_path.relative_to(features_dir)
        provider = _provider_from_context(rel_path, feature_tags)
        concern = _concern_from_path(rel_path)

        for node in _iter_scenario_nodes(feature):
            scenario_obj = node["scenario"]
            scenario_name = scenario_obj.get("name", "Unnamed")
            keyword = scenario_obj.get("keyword", "Scenario")
            text = _scenario_step_text(scenario_obj)
            resolution_key = _extract_resolution_key(text)
            country = _extract_country(text)
            zone = _extract_zone(text, provider, country, porto_data_path=porto_data_path)
            slice_name = _infer_slice(scenario_name, text, keyword)
            cell_id = _make_cell_id(
                provider, concern, slice_name, resolution_key, zone, scenario_name, used_ids
            )

            cells.append(
                {
                    "cell_id": cell_id,
                    "provider": provider,
                    "concern": concern,
                    "slice": slice_name,
                    "product_id": resolution_key,
                    "zone": zone,
                    "status": "required",
                    "refs": [_matrix_ref(rel_path, keyword, scenario_name)],
                }
            )

    return cells


def dump_sdk_yaml(cells: list[dict[str, Any]]) -> str:
    lines = [FILE_HEADER.rstrip("\n")]
    for cell in cells:
        lines.append(f"  - cell_id: {cell['cell_id']}")
        lines.append(f"    provider: {cell['provider']}")
        lines.append(f"    concern: {cell['concern']}")
        lines.append(f"    slice: {cell['slice']}")
        product_id = cell["product_id"]
        zone = cell["zone"]
        lines.append(f"    product_id: {product_id if product_id is not None else 'null'}")
        lines.append(f"    zone: {zone if zone is not None else 'null'}")
        lines.append("    status: required")
        lines.append("    refs:")
        for ref in cell["refs"]:
            lines.append(f"      - {ref}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_sdk_matrix(
    features_dir: Path,
    output_path: Path,
    *,
    porto_data_path: Path | None = None,
) -> int:
    cells = scan_sdk_features(features_dir, porto_data_path=porto_data_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(dump_sdk_yaml(cells), encoding="utf-8")
    return len(cells)
